import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WalletContextProvider from "./components/WalletProvider";
import { WalletIcon } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="wallet p-4 bg-zinc-800 border border-zinc-600 cursor-pointer rounded-full w-fit absolute right-0 m-4"><WalletIcon className="text-white"/></div>
        <WalletContextProvider>{children}</WalletContextProvider>{" "}
      </body>
    </html>
  );
}
